apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk18
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        description: >-
          Build and run Java Microservices such as Spring Noot
        iconClass: icon-spring
        openshift.io/display-name: OpenJDK 1.8 S2I image(Latest)
        openshift.io/provider-display-name: 'Fabric8'
        tags: 'builder,java,spring-boot'
      from:
        kind: DockerImage
        name: fabric8/s2i-java
      name: latest
      referencePolicy:
        type: Source
